### ISSUE TITLE
Eliminate external JSON export script

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#144]
### Dependency
- PR #141, which introduces the external script

### Overview
We're using an external Goggle Apps script to export initial data from the spreadsheet in JSON form, but the functionality can be brought in to our own script and eliminate the manual step.
 - from #36, which uses the external script

### Action Items

- [x] Create a Python script to read sheets data
  - [ ] Read all the data from a sheet by sheet name
- [x] Combine or call the script from the initial data conversion script
  - [x] Make sure the new setup works for SOC Major and User Status data
  - [ ] Bonus: call the conversion script with the model name as input and have it output to a file named after the model
- [x] Remove external script and associated docs

### Resources/Instructions
- [Google Sheets python quickstart](https://developers.google.com/sheets/api/quickstart/python)

**Comment by anandramakris** [comment]
Have modified the data conversion script so it reads data directly from a csv, but it is not able to gather data sheet by sheet yet.

**Comment by anandramakris** [comment]
Have created a new pull request. The documentation has been modified to show that the file can be read without changing the name of the file.

I figured out why Pandas reading from Google Sheets directly did not work. Even if you specify the gid of the sheet, it always reads from the first sheet in each spreadsheet - in the case of "PD: Table and field explanations" it always reads from "what  happens re github and reminders." Since the rows in that sheet have different numbers of elements, it caused a null value error.

**Comment by fyliu** [comment]
I might have manually merged the changes into `main`. Adding the "dev lead" label to check later.

**Comment by fyliu** [comment]
- Yes, it's been manually merged according to PR #280
Closing this issue as done.
