### ISSUE TITLE
Install Django Linear Migrations package.

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/peopledepot#215]
### Overview
We want to install this package to ensure your migration history is linear and help us with merge conflicts.

### Action Items
- [x] Read the documentation 
- [x] Try to install it on our repo
- [ ] If you need higher level of repo permissions, reach out in the Admin Slack channel with your request.
- [x] Test by resolving the merge conflicts in an issue that has been approved for merging. (not including issue #193)

### Resources/Instructions
https://github.com/adamchainz/django-linear-migrations

**Comment by fyliu** [comment]
I'm taking this issue since it's better to have it sooner rather than later.

The setup is straightforward from the readme.
I had to set it up on both `main` and the incoming feature branch for merging. It only works if the check file `max_migration.txt` exists in both branches to create the conflict condition.

It doesn't prevent the conflict but it makes it appear in git, which is more convenient than the way we have it currently, which is in a pre-commit hook.

After the conflict happens on the git rebase, the `rebase_migration` command puts the incoming migration file at the end of the migration chain.

I'm not sure how this can be tested best. I can create the pre-rebased and then the reviewer can check that the rebase creates a conflict and that the `rebase_migration` command will resolve the conflict the way it should.

**Comment by fyliu** [comment]
I'm down to the last reviewable PR #216. The commit with the migration file must be AFTER the django-linear-migrations setup. So I would need to insert the setup commit before Alex's PR code and then update his commit with a newly-generated max_migration.txt file. At that point, Alex's code will have a 0017 and main will have a different 0017. Rebasing them will create a git merge conflict, and running manage.py rebase_migration core should fix it automatically.

**Comment by fyliu** [comment]
Steps to show this working:

```bash
# fetch from remote for fang
git fetch <remote name for fang>

# delete the db volume
docker-compose down -v

# Checkout the dlm main branch
git checkout fang/dlm-1-main
# run buildrun.sh
./scripts/buildrun.sh

# 
3. checkout the dlm 2 feature branch
4. run git rebase dlm-1-main
```
