### ISSUE TITLE
API for creating and getting users without authenticating (server job)

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/peopledepot#260]
### Overview

This is a knowledgebase requirement to allow synchronization of users table without having to rely on permissions of a user.

**Comment by fyliu** [comment]
@ethanstrominger
This issue likely needs to be broken down into several steps

- specify how and why for create user API (or is it users?)
- specify how and why for get user API (or is it users?)
- add "server job" functionality to PD
- implement create user API for server job
- implement get user API for server job

I have many questions since the description wasn't clear:

- What user data need to be synchronized in what direction?
- Why does KB's backend need to create PD users?
- Why does KB's backend need to get users?
- Why doesn't all this happen when the individual user use the system using the user' own permission?
