### ISSUE TITLE
Add 'missing' labels to new issue templates

### ISSUE THREAD

**Issue by shmonks** [hackforla/peopledepot#364]
### Dependencies
- [x] BW releases org-wide rules for formatting labels

### Overview

We need to add `: missing` labels to those templates for new issues which lack them, in order to regularize, encourage, and review issue description.

### Action Items

- [x] Look through each of the [PD new issue templates](https://github.com/hackforla/peopledepot/tree/main/.github/ISSUE_TEMPLATE) 
- [x] Add any missing `: missing` labels from the following list:
    - [ ] role: missing
    - [ ] size: missing
    - [ ] complexity: missing
    - [x] feature: missing
    - [x] milestone: missing

### Resources/Instructions

- [PD New Issue page](https://github.com/hackforla/peopledepot/issues/new/choose)
- https://github.com/hackforla/HomeUniteUs/issues/354#issuecomment-2266008319

**Comment by shmonks** [comment]
Please consider the following questions and add an update below:
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
- Issue Template: [Add seed data to a table](https://github.com/hackforla/peopledepot/issues/new?assignees=&labels=good+first+issue%2C+role%3A+back+end%2C+s%3A+CTJ%2C+s%3A+hackforla.org%2C+s%3A+kb%2C+s%3A+org%2C+s%3A+PD+team%2C+s%3A+tables%2C+s%3A+VRMS%2C+size%3A+1pt&projects=&template=add-seed-data-to-a-table.md&title=Add+seed+data+for+Table%3A+%5BReplace+with+TABLE+NAME%5D)
   - it has all the stakeholder labels, instead of just having the stakeholder missing label.  So it requires the person to remove inaccurate ones, but there is no instruction to do that.  We prefer to replace the stakeholder labels with stakeholder missing
   - it has a role label and the role label missing.  Remove the role missing
- [Control what appears when you paste your sites link in social media sites](https://github.com/hackforla/peopledepot/issues/new?assignees=&labels=enhancement%2C+question&projects=&template=control-what-appears-when-you-paste-your-sites-link-in-social-media-sites.md&title=Control+what+appears+when+you+paste+your+sites+link+in+social+media+sites)
   - Bonnie needs to decide what labels this gets
- [Create Agenda](https://github.com/hackforla/peopledepot/issues/new?assignees=&labels=documentation%2C+help+wanted%2C+question&projects=&template=create-agenda.md&title=)
   - This is an old template, it should be replaced with a new template.  Discuss with Bonnie
- [Create Table Issue Form](https://github.com/hackforla/peopledepot/issues/new?assignees=&labels=feature%3A+table+creation%2Crole%3A+back+end%2Csize%3A+2pt&projects=&template=create-table-issue-form.yml&title=Create+Table%3A+%5Bname+of+table%5D)
  - missing some missing labels

**Comment by ExperimentsInHonesty** [comment]
- [ ] 'complexity: missing, 
- [ ] feature: missing, 
- [ ] milestone: missing, 
- [ ] points: missing,
- [ ] role: missing, 
- [ ] size: missing, 
- [ ] stakeholder: missing'
