### ISSUE TITLE
Merge Fang's fork of People Depot 

### ISSUE THREAD

**Issue by JasonEb** [hackforla/peopledepot#4]
### Overview
We need to merge Fang's branch into the initial repo so that other developers can build on it. 

### Action Items
- [ ] PR Fang's People Depot Fork
- [ ] Review 
- [ ] Merge it 
- [ ] Test if people can `git clone` and run the dockerized `app` 
   - [ ] Test Dockerized People Depot on OSX : Alpesh and Nicole 
   - [ ] Test Dockerized People Depot on Windows : Junyeob, Jason, and Carter

### Resources/Instructions
The People Depot app will be a Django application using PostgreSQL. This should be modeled after https://github.com/fyliu/django-tdd-docker/tree/main/app

[Fang's Fork](https://github.com/fyliu/peopledepot/tree/4-setup)

[Project Notes](https://docs.google.com/document/d/19rwvB6tMWwquCvS59k5kUOxEyRiUdr0Wx4VgIIsz0Vo/edit#heading=h.owxtvgn5o1fn)

**Comment by fyliu** [comment]
I made the pull request. I requested reviews from Alpesh and Nicole. I hope this was the group that should go first.

I'm not sure how familiar you are with testing pull requests, but here's what I would do for this one:
1. Check out Fang's code from the [fork](https://github.com/fyliu/peopledepot/tree/4-setup) (set up the fyliu repo as a git remote to switch between the forks easily)
2. Try to follow the README installation instructions and make notes of anything that's broken, unclear or needs further explanation
3. Check that everything is there (this initial code has many parts, so the dev needs to make a list of what to look for)
    - [ ] The docker-compose command spins up the containers without errors
    - [ ] The site loads at localhost:8000 (it's just a default page that's not blank)
    - [ ] Can login to the admin area at localhost:8000/admin to add and change users
      - [ ] CustomUser model is showing up
    - [ ] Can run pytest tests without errors
4. Click on the pull request page and write and submit a review (maybe copy the checklist above and add anything else)

Don't close the pull request until the last reviewer has done a review. Closing the pull request would automatically merge the code, since I tagged issue #4 at the bottom of my pull request description.

I just realized there's missing instructions for half the items in the checklist. If I don't get a chance to add them to the pull request before someone reviews it. just note them in the reviews and I will add them to contributing.md. I just wanted to put in the pull request ASAP so I'm not blocking others.

**Comment by fyliu** [comment]
I think it'll be easier to review now.

I just pushed some changes:
- redid some commits to
  - change the django project name to peopledepot
  - change custom user to User
  - comment out running migrations in entrypoint script
- updated readme with
  - more details
  - instruction on running migrations and tests as well as the web admin
