### ISSUE TITLE
Technical: make testing faster

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/peopledepot#414]
### Overview

Speed of testing has significant impact on development - more than just the time that it takes, it interrupts the flow.  

There are three ways to speed it up:
- provide option to skip migration
- use pytest-xdist package and "-n auto" option to run tests in parallel
- by default, skip coverage and provide option to enable it

**Comment by fyliu** [comment]
I see these are quick ways to speed up the tests.

Any general idea how long the tests take to run currently and how much these measures speed it up? Having the expected savings for each measure is useful for a developer to decide what to enable/disable. If it's reducing the run time to 1/8 with a quad-core hyperthreaded CPU (8 virtual processors), then we can expect not worry about speed again until we added 8x the tests we have now.

A root cause of the slowness is that the tests are accessing the database every time. A great way to speed up tests is to make each test run faster by not accessing the database. It's also not quick.

**Comment by ethanstrominger** [comment]
Previously, tests took about 30 seconds to run.  Skipping migration saves about 5 seconds and using the default -n option saves 10 seconds - both together make it twice as fast.
