### ISSUE TITLE
Create Table: project_sdg_xref

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/peopledepot#66]
### Dependency
 - #16 
 - #70

### Overview

We need to create the project_sdg_xref table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [x] create a single model in Django (defining schema)
- [x] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [x] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Joins and SDG to a project

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

    - [x] (PK) id - int - Record Id
    - [x] (FK) sdg_id - int - id of sdg linked to project
    - [x] (FK) project_id - int - id of project linked to sdg
    - [x] ended_on - date

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] sdg (many-to-one)
   - [x] project (many-to-one)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by dmartin4820** [comment]
@fyliu As we discussed on Thursday, I took a look at the backlog and this is an issue I'd be willing to take on. Should be similar to the last issue I did. 

There are a few differences in the issue description above compared to the Table and Field definitions Excel sheet and the ERD. Specifically, they are differences in the ERD types and the issue description, and differences in the table relationships in the Table and Field definitions Excel sheet. I can check in more detail and update if I take this task on.

**Comment by fyliu** [comment]
@dmartin4820 Ah, yeah, I think we made all the create table issues before deciding to use `uuid` everywhere. So everything says `int` but means `uuid`. I kind of don't want to go through and change everything right now in case something changes later. Maybe when we finish all the create table issues we should look at updating the ERD and spreadsheet, since those are really our source of truth for the design.

If you want to add notes somewhere in the documentation so that new people understand what's going on, that'd be great to have.

**Comment by dmartin4820** [comment]
@fyliu Is ended the same thing as ```updated_at```? Currently the AbstractBaseModel has ```created_at``` and ```updated_at```, but doesn't contain "ended_on". 

If it is the same as ```updated_at```, then the ERD should be updated. I can also update the issue here as well. Otherwise, I can create the field, specific to the ```project_sdg_xref``` model.

**Comment by fyliu** [comment]
This table doesn't need a Django model. See [this comment](https://github.com/hackforla/peopledepot/issues/205#issuecomment-1984928630).

**Comment by fyliu** [comment]
@dmartin4820 I'm not sure. We should ask @Neecolaa or @ExperimentsInHonesty 

I'll move this issue to the Questions column with the "ready for Architect" label and add an item in the Agenda

**Comment by dmartin4820** [comment]
> @dmartin4820 I'm not sure. We should ask @Neecolaa or @ExperimentsInHonesty
> 
> You should move this issue to the Questions column with the "ready for Architect" label and add an item in the Agenda

Ok, so if we find that ```ended_on``` is different than ```created_at``` and ```updated_at```, I'll create the model with just the ```ended_on``` field. If not, the model doesn't need to be created since the other fields in the ERD are in AbstractBaseModel and the model relationships may be able to be specified another way, without creating a model with the relationships defined (still need to figure out how this is done in Django).

**Comment by Neecolaa** [comment]
@fyliu @dmartin4820 
`ended_on` is different from `updated_at`

`ended_on` notes when the relationship between the project and the SDG ended (the project is no longer working towards that Sustainable Development Goal). If the project is still actively working towards that SDG, `ended_on` would be `null`.

`updated_at` is just the last time any field in that record was updated

That said, I'd still like to ask Bonnie if this relationship needs an `ended_on` field. Do projects change SDGs? 
(Since that's not a field that all tables had at some point, the answer is likely "yes")

**Comment by dmartin4820** [comment]
@fyliu I'm still working on implementing the project_sdg_xref table. You can view my working modifications [here](https://github.com/hackforla/peopledepot/compare/main...dmartin4820:peopledepot:create_table_project_sdg_xref_66)

Currently, I'm trying to think about how to implement tests in ```app/core/tests/test_api.py```.  At a high level, I'm thinking that we would have some request (POST?) to update the Project and SDG models by creating a relationship between the two. Not sure how I'm going to implement it yet, but I'm open to suggestions on that topic, or on other modifications I made in the ```create_table_project_sdg_xref_66``` branch.

**Comment by dmartin4820** [comment]
For weekly meeting today 

Progress: Got reviews the PR. I need to just implement the changes comments. 
Blockers: None yet
Availability: Flexible between 5pm - 9pm on weekdays.
ETA: Will work between tomorrow and over the weekend

**Comment by dmartin4820** [comment]
For 10/24/2024 meeting:
I won't be at the meeting tomorrow

Progress: Got reviews from Fang and Del. Thanks to both for the useful suggestions/changes.
Blockers: None yet just have to go make the suggested changes
Availability: Flexible between 5pm - 9pm on weekdays.
ETA: Will work over the weekend
